trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseGoVersion@0
  inputs:
    version: '1.x'
    addToPath: true

- script: |
    go mod tidy
  displayName: 'Ensure dependencies'

- script: |
    go test -v ./...
  displayName: 'Run tests'

- script: |
    go build -o myapp .
  displayName: 'Build application'

- script: |
    ./myapp &
    sleep 5
  displayName: 'Run service'

- script: |
    curl http://localhost:8080
  displayName: 'Test service'
